### ISSUE TITLE
cwlexec doesn't support inputs of type Array<enum>

### ISSUE THREAD

**Issue by mscheremetjew** [IBMSpectrumComputing/cwlexec#30]
cwlexec reports the following and exits:
The variable type of the field [type] is not valid, "a valid CWL type" is required.

if the input port is defined like that:
```
inputs:
  - id: applications
    type:
      type: array
      items:
        type: enum
        name: applications
        symbols:
          - PfamA
          - TIGRFAM
```
on the other hand cwltool & cwl-runner is accepting those type definitions.
