### ISSUE TITLE
SchemaDefRequirement section: Imports of type definitions are not supported

### ISSUE THREAD

**Issue by mscheremetjew** [IBMSpectrumComputing/cwlexec#32]
cwlexec reports the following and exits:
```
The field [SchemaType] is required by [type].
```
if a type definition is imported like that:
```
cwlVersion: v1.0
class: CommandLineTool

requirements:
 - class: SchemaDefRequirement
   types:
    - $import: test_values.yaml
```
here is a simple test case for reproduction:
[test.cwl.txt](https://github.com/IBMSpectrumComputing/cwlexec/files/2428363/test.cwl.txt)
[test.yaml.txt](https://github.com/IBMSpectrumComputing/cwlexec/files/2428364/test.yaml.txt)
[test_values.yaml.txt](https://github.com/IBMSpectrumComputing/cwlexec/files/2428365/test_values.yaml.txt)

call:
```
$ cwlexec test.cwl test.yaml
```
